---
language: ruby
script: "bundle exec rubytest -v -Ilib test/"
bundler_args: --without guard
rvm:
  - 2.3.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - rbx
  - jruby
matrix:
  allow_failures:
    - rvm: rbx
cache: bundler
